[package]
name = "echo-li-python"
version = "0.1.0"
edition = "2024"

[lib]
name = "_echo_li"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
numpy = "0.25"
echo-li-core = { path = "../echo-li-core" }
echo-lie.workspace = true
rudolf-v.workspace = true
nalgebra.workspace = true
